### ISSUE TITLE
Symbolizing American Rivers dams

### ISSUE THREAD

**Issue by skybristol** [AppGeo/usgs-drip#1]
The dams table in the database has a field called AR_UNIQUEID. This probably isn't the best place for this information, but we can use it for now. We did synthesize two different databases of dams into this table, so there are both dams from American Rivers and those that USGS put together from other sources. It would be good to symbolize these differently, perhaps just with different colors for the dots, and provide a legend with a label of "Data Reference." Anything with a value in AR_UNIQUEID should be attributed to "American Rivers" in Data Reference. Records without a value for AR_UNIQUEID should be attributed to "USGS Powell Center" for now until we decide how we want to better classify the records.

**Comment by ismyrnow** [comment]
Ahh, I was wondering how to differentiate between dams from the two databases. Symbolizing based on this is doable.

**Comment by ismyrnow** [comment]
Closing this out since they're now symbolized separately.
